name: Readme Generator

on:
  push:
    branches:
      - production
      - develop
    paths:
      - '.github/md-generator/md-generator.py'
      - 'icons/**'
  workflow_run:
    workflows: ["SketchTool Export Assets"]
    types: 
      - completed

jobs:
  regenerating:
    runs-on: [self-hosted, Linux]

    steps:
    # comando solo para Self-Hosted machines
    # - run: sudo chown -R $USER:$USER /home/pi/actions-runner/_work/
    - name: Cleanup
      run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - name: Get branch name
      uses: rlespinasse/github-slug-action@v3.x

    - uses: actions/checkout@v2
    
    # no se necesita actions/python en self-hosted
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    
    - run: sudo python .github/md-generator/md-generator.py icons

    - name: stage changed files
      run: git add -f .

    - name: config
      run: |
        git config --global user.name "🤖GeneratorBot"
        git config --global user.email "users.noreply.github.com"

    - name: commit changed files
      run: git commit -m "Auto updating Readme"

    - name: push code to ${{ env.GITHUB_REF_SLUG_URL }}
      run: git push origin HEAD:${{ env.GITHUB_REF_SLUG_URL }}