name: Readme Generator

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/md-generator/md-generator.py'
      - '.github/workflows/auto-generator.yml'
      - 'icons/'

jobs:
  regenerating:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get branch name
        uses: rlespinasse/github-slug-action@v3.x

      - run: sudo python3 .github/md-generator/md-generator.py icons

      - name: Commit & Push
        run: |
          git config user.name "Mística Bot"
          git config user.email "nobody@nowhere"  
          git commit -am "Update readme"

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.NOVUM_PRIVATE_REPOS }}
          branch: production
          unprotect_reviews: true