name: Copy-New

on: push

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_branch: production
        src_path: icn_export/
        dst_path: ./
        dst_owner: mistica-icons
        dst_repo_name: mistica-icons.github.io
        clean: false
