name: Cloning icn_export to mistica-icon-web

on: push

jobs:
  copy:
    runs-on: self-hosted
    steps:
    - name: Copy
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_branch: production
        src_path: /icn_export/.
        dst_path: /icn_export/.
        dst_owner: Telefonica
        dst_repo_name: mistica-icons-web
        clean: true
