name: Buscar palabra en archivos SVG y actualizar comentario de la PR

on:
  pull_request:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Buscar palabra en archivos SVG
        id: buscar-palabra
        run: |
          files_with_evenodd=""
          for file in $(find icons -name "*.svg"); do
            if grep -q "evenodd" "$file"; then
              echo "Se encontró la palabra 'evenodd' en $file"
              files_with_evenodd="${files_with_evenodd}${file}\n"
            fi
          done
          if [ -n "$files_with_evenodd" ]; then
            echo -e "::set-output name=evenodd_files::${files_with_evenodd}"
            echo -e "Archivos con 'evenodd':\n${files_with_evenodd}"
            exit 0
          fi

      - name: Actualizar comentario de la PR
        if: ${{ github.event_name == 'pull_request' && steps.buscar-palabra.outcome != 'failure' }}
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.NOVUM_PRIVATE_REPOS }}
          script: |
            const evenoddFiles = '${{ steps.evenodd.outputs.evenodd_files }}';
            const prNumber = context.payload.pull_request.number;
            const body = `Archivos con 'evenodd':\n${evenoddFiles}`;

            const { data: comments } = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            const existingComment = comments.find(comment => comment.user.login === 'github-actions[bot]' && comment.body.startsWith('Archivos con \'evenodd\':'));
            if (existingComment) {
              await github.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body,
              });
            } else {
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body,
              });
            }

            if (evenoddFiles) {
              core.setFailed("Se encontró la palabra 'evenodd' en los archivos");
            }
