name: SketchTool Export Assets

on:
  push:
    branches:
    - brandFactory-icons
    # paths:
    # - '_library/**'
    
jobs:
  assets:
    runs-on: [self-hosted, macOS]
    steps:
    - uses: actions/checkout@v2

    - name: Install svgo
      run: npm install -g svgo

    - name: Removed assets
      run: git rm -r brandFactory_export/*
    
    - run: npm install --global kactus-cli

    - name: Convert folder to sketch file
      run: kactus import _library/POC_MisticaIcons_BF

    - name: Download & Install Sketch
      run: |
        curl -OL https://sketch.com/download/sketch.zip
        unzip sketch.zip

    - name: Run SketchTool
      run: Sketch.app/Contents/Resources/sketchtool/bin/sketchtool export layers --output=brandFactory_export _library/*.sketch

    - name: SVGO
      run: svgo -f brandFactory_export/ --disable=removeViewBox

    - name: Add assets
      run: git add -A brandFactory_export/*

    - name: Commit
      run: |    
        git config --global user.name "Yayo"
        git config --global user.email "yceballost@gmail.com"  
        git commit -am "Update Assets"

    - name: Push
      run: |
        git show-ref
        git push origin HEAD:brandFactory-icons
        