name: SketchTool Export Assets

on:
  push:
    paths:
      - ".github/workflows/export-assets-figma.yml"

jobs:
  all:
    name: Figma Export
    runs-on: ubuntu-latest
    steps:
      - uses: primer/figma-action@v1.0.0-alpha.2
        with:
          args: "format=svg outputDir=./FigmaTest/"
        env:
          FIGMA_FILE_URL: "https://www.figma.com/file/JHuzksh01yxExMeMQBvymq/Mistica-Icons"
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
